// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginType int32

const (
	PluginType_UNKNOWN      PluginType = 0
	PluginType_AWS_IAM_USER PluginType = 1
	PluginType_AZURE        PluginType = 2
	PluginType_BITDEFENDER  PluginType = 3
	PluginType_GCP          PluginType = 4
	PluginType_O365         PluginType = 5
	PluginType_SOC_AI       PluginType = 6
	PluginType_SOPHOS       PluginType = 7
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "UNKNOWN",
		1: "AWS_IAM_USER",
		2: "AZURE",
		3: "BITDEFENDER",
		4: "GCP",
		5: "O365",
		6: "SOC_AI",
		7: "SOPHOS",
	}
	PluginType_value = map[string]int32{
		"UNKNOWN":      0,
		"AWS_IAM_USER": 1,
		"AZURE":        2,
		"BITDEFENDER":  3,
		"GCP":          4,
		"O365":         5,
		"SOC_AI":       6,
		"SOPHOS":       7,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type BiDirectionalMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BiDirectionalMessage_PluginInit
	//	*BiDirectionalMessage_Config
	Payload       isBiDirectionalMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BiDirectionalMessage) Reset() {
	*x = BiDirectionalMessage{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiDirectionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDirectionalMessage) ProtoMessage() {}

func (x *BiDirectionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDirectionalMessage.ProtoReflect.Descriptor instead.
func (*BiDirectionalMessage) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *BiDirectionalMessage) GetPayload() isBiDirectionalMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BiDirectionalMessage) GetPluginInit() *PluginInit {
	if x != nil {
		if x, ok := x.Payload.(*BiDirectionalMessage_PluginInit); ok {
			return x.PluginInit
		}
	}
	return nil
}

func (x *BiDirectionalMessage) GetConfig() *ConfigurationSection {
	if x != nil {
		if x, ok := x.Payload.(*BiDirectionalMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isBiDirectionalMessage_Payload interface {
	isBiDirectionalMessage_Payload()
}

type BiDirectionalMessage_PluginInit struct {
	PluginInit *PluginInit `protobuf:"bytes,1,opt,name=plugin_init,json=pluginInit,proto3,oneof"`
}

type BiDirectionalMessage_Config struct {
	Config *ConfigurationSection `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

func (*BiDirectionalMessage_PluginInit) isBiDirectionalMessage_Payload() {}

func (*BiDirectionalMessage_Config) isBiDirectionalMessage_Payload() {}

type PluginInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PluginType             `protobuf:"varint,1,opt,name=type,proto3,enum=config.PluginType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInit) Reset() {
	*x = PluginInit{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInit) ProtoMessage() {}

func (x *PluginInit) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInit.ProtoReflect.Descriptor instead.
func (*PluginInit) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInit) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_UNKNOWN
}

type Configuration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId         int32                  `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ConfKey         string                 `protobuf:"bytes,3,opt,name=confKey,proto3" json:"confKey,omitempty"`
	ConfValue       string                 `protobuf:"bytes,4,opt,name=confValue,proto3" json:"confValue,omitempty"`
	ConfName        string                 `protobuf:"bytes,5,opt,name=confName,proto3" json:"confName,omitempty"`
	ConfDescription string                 `protobuf:"bytes,6,opt,name=confDescription,proto3" json:"confDescription,omitempty"`
	ConfDataType    string                 `protobuf:"bytes,7,opt,name=confDataType,proto3" json:"confDataType,omitempty"`
	ConfRequired    bool                   `protobuf:"varint,8,opt,name=confRequired,proto3" json:"confRequired,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Configuration) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Configuration) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Configuration) GetConfKey() string {
	if x != nil {
		return x.ConfKey
	}
	return ""
}

func (x *Configuration) GetConfValue() string {
	if x != nil {
		return x.ConfValue
	}
	return ""
}

func (x *Configuration) GetConfName() string {
	if x != nil {
		return x.ConfName
	}
	return ""
}

func (x *Configuration) GetConfDescription() string {
	if x != nil {
		return x.ConfDescription
	}
	return ""
}

func (x *Configuration) GetConfDataType() string {
	if x != nil {
		return x.ConfDataType
	}
	return ""
}

func (x *Configuration) GetConfRequired() bool {
	if x != nil {
		return x.ConfRequired
	}
	return false
}

type ModuleGroup struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleId                  int32                  `protobuf:"varint,2,opt,name=moduleId,proto3" json:"moduleId,omitempty"`
	GroupName                 string                 `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	GroupDescription          string                 `protobuf:"bytes,4,opt,name=groupDescription,proto3" json:"groupDescription,omitempty"`
	ModuleGroupConfigurations []*Configuration       `protobuf:"bytes,5,rep,name=moduleGroupConfigurations,proto3" json:"moduleGroupConfigurations,omitempty"`
	Collector                 string                 `protobuf:"bytes,6,opt,name=collector,proto3" json:"collector,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ModuleGroup) Reset() {
	*x = ModuleGroup{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleGroup) ProtoMessage() {}

func (x *ModuleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleGroup.ProtoReflect.Descriptor instead.
func (*ModuleGroup) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleGroup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModuleGroup) GetModuleId() int32 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *ModuleGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ModuleGroup) GetGroupDescription() string {
	if x != nil {
		return x.GroupDescription
	}
	return ""
}

func (x *ModuleGroup) GetModuleGroupConfigurations() []*Configuration {
	if x != nil {
		return x.ModuleGroupConfigurations
	}
	return nil
}

func (x *ModuleGroup) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

type ConfigurationSection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId          int32                  `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	PrettyName        string                 `protobuf:"bytes,3,opt,name=prettyName,proto3" json:"prettyName,omitempty"`
	ModuleName        string                 `protobuf:"bytes,4,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	ModuleDescription string                 `protobuf:"bytes,5,opt,name=moduleDescription,proto3" json:"moduleDescription,omitempty"`
	ModuleActive      bool                   `protobuf:"varint,6,opt,name=moduleActive,proto3" json:"moduleActive,omitempty"`
	ModuleIcon        string                 `protobuf:"bytes,7,opt,name=moduleIcon,proto3" json:"moduleIcon,omitempty"`
	ModuleCategory    string                 `protobuf:"bytes,8,opt,name=moduleCategory,proto3" json:"moduleCategory,omitempty"`
	LiteVersion       bool                   `protobuf:"varint,9,opt,name=liteVersion,proto3" json:"liteVersion,omitempty"`
	NeedsRestart      bool                   `protobuf:"varint,10,opt,name=needsRestart,proto3" json:"needsRestart,omitempty"`
	ModuleGroups      []*ModuleGroup         `protobuf:"bytes,11,rep,name=moduleGroups,proto3" json:"moduleGroups,omitempty"`
	Activatable       bool                   `protobuf:"varint,12,opt,name=activatable,proto3" json:"activatable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigurationSection) Reset() {
	*x = ConfigurationSection{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSection) ProtoMessage() {}

func (x *ConfigurationSection) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSection.ProtoReflect.Descriptor instead.
func (*ConfigurationSection) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigurationSection) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigurationSection) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ConfigurationSection) GetPrettyName() string {
	if x != nil {
		return x.PrettyName
	}
	return ""
}

func (x *ConfigurationSection) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ConfigurationSection) GetModuleDescription() string {
	if x != nil {
		return x.ModuleDescription
	}
	return ""
}

func (x *ConfigurationSection) GetModuleActive() bool {
	if x != nil {
		return x.ModuleActive
	}
	return false
}

func (x *ConfigurationSection) GetModuleIcon() string {
	if x != nil {
		return x.ModuleIcon
	}
	return ""
}

func (x *ConfigurationSection) GetModuleCategory() string {
	if x != nil {
		return x.ModuleCategory
	}
	return ""
}

func (x *ConfigurationSection) GetLiteVersion() bool {
	if x != nil {
		return x.LiteVersion
	}
	return false
}

func (x *ConfigurationSection) GetNeedsRestart() bool {
	if x != nil {
		return x.NeedsRestart
	}
	return false
}

func (x *ConfigurationSection) GetModuleGroups() []*ModuleGroup {
	if x != nil {
		return x.ModuleGroups
	}
	return nil
}

func (x *ConfigurationSection) GetActivatable() bool {
	if x != nil {
		return x.Activatable
	}
	return false
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\"\x90\x01\n" +
	"\x14BiDirectionalMessage\x125\n" +
	"\vplugin_init\x18\x01 \x01(\v2\x12.config.PluginInitH\x00R\n" +
	"pluginInit\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.config.ConfigurationSectionH\x00R\x06configB\t\n" +
	"\apayload\"4\n" +
	"\n" +
	"PluginInit\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.config.PluginTypeR\x04type\"\xff\x01\n" +
	"\rConfiguration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\x05R\agroupId\x12\x18\n" +
	"\aconfKey\x18\x03 \x01(\tR\aconfKey\x12\x1c\n" +
	"\tconfValue\x18\x04 \x01(\tR\tconfValue\x12\x1a\n" +
	"\bconfName\x18\x05 \x01(\tR\bconfName\x12(\n" +
	"\x0fconfDescription\x18\x06 \x01(\tR\x0fconfDescription\x12\"\n" +
	"\fconfDataType\x18\a \x01(\tR\fconfDataType\x12\"\n" +
	"\fconfRequired\x18\b \x01(\bR\fconfRequired\"\xf6\x01\n" +
	"\vModuleGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bmoduleId\x18\x02 \x01(\x05R\bmoduleId\x12\x1c\n" +
	"\tgroupName\x18\x03 \x01(\tR\tgroupName\x12*\n" +
	"\x10groupDescription\x18\x04 \x01(\tR\x10groupDescription\x12S\n" +
	"\x19moduleGroupConfigurations\x18\x05 \x03(\v2\x15.config.ConfigurationR\x19moduleGroupConfigurations\x12\x1c\n" +
	"\tcollector\x18\x06 \x01(\tR\tcollector\"\xbd\x03\n" +
	"\x14ConfigurationSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bserverId\x18\x02 \x01(\x05R\bserverId\x12\x1e\n" +
	"\n" +
	"prettyName\x18\x03 \x01(\tR\n" +
	"prettyName\x12\x1e\n" +
	"\n" +
	"moduleName\x18\x04 \x01(\tR\n" +
	"moduleName\x12,\n" +
	"\x11moduleDescription\x18\x05 \x01(\tR\x11moduleDescription\x12\"\n" +
	"\fmoduleActive\x18\x06 \x01(\bR\fmoduleActive\x12\x1e\n" +
	"\n" +
	"moduleIcon\x18\a \x01(\tR\n" +
	"moduleIcon\x12&\n" +
	"\x0emoduleCategory\x18\b \x01(\tR\x0emoduleCategory\x12 \n" +
	"\vliteVersion\x18\t \x01(\bR\vliteVersion\x12\"\n" +
	"\fneedsRestart\x18\n" +
	" \x01(\bR\fneedsRestart\x127\n" +
	"\fmoduleGroups\x18\v \x03(\v2\x13.config.ModuleGroupR\fmoduleGroups\x12 \n" +
	"\vactivatable\x18\f \x01(\bR\vactivatable*r\n" +
	"\n" +
	"PluginType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fAWS_IAM_USER\x10\x01\x12\t\n" +
	"\x05AZURE\x10\x02\x12\x0f\n" +
	"\vBITDEFENDER\x10\x03\x12\a\n" +
	"\x03GCP\x10\x04\x12\b\n" +
	"\x04O365\x10\x05\x12\n" +
	"\n" +
	"\x06SOC_AI\x10\x06\x12\n" +
	"\n" +
	"\x06SOPHOS\x10\a2_\n" +
	"\rConfigService\x12N\n" +
	"\fStreamConfig\x12\x1c.config.BiDirectionalMessage\x1a\x1c.config.BiDirectionalMessage(\x010\x01B<Z:github.com/utmstack/UTMStack/plugins/modules-config/configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_proto_goTypes = []any{
	(PluginType)(0),              // 0: config.PluginType
	(*BiDirectionalMessage)(nil), // 1: config.BiDirectionalMessage
	(*PluginInit)(nil),           // 2: config.PluginInit
	(*Configuration)(nil),        // 3: config.Configuration
	(*ModuleGroup)(nil),          // 4: config.ModuleGroup
	(*ConfigurationSection)(nil), // 5: config.ConfigurationSection
}
var file_config_proto_depIdxs = []int32{
	2, // 0: config.BiDirectionalMessage.plugin_init:type_name -> config.PluginInit
	5, // 1: config.BiDirectionalMessage.config:type_name -> config.ConfigurationSection
	0, // 2: config.PluginInit.type:type_name -> config.PluginType
	3, // 3: config.ModuleGroup.moduleGroupConfigurations:type_name -> config.Configuration
	4, // 4: config.ConfigurationSection.moduleGroups:type_name -> config.ModuleGroup
	1, // 5: config.ConfigService.StreamConfig:input_type -> config.BiDirectionalMessage
	1, // 6: config.ConfigService.StreamConfig:output_type -> config.BiDirectionalMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[0].OneofWrappers = []any{
		(*BiDirectionalMessage_PluginInit)(nil),
		(*BiDirectionalMessage_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
