# Elasticsearch filter, version 3.0.1
# Fields based on https://www.elastic.co/guide/en/elasticsearch/reference/8.17/audit-event-types.html, 
# https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-module-elasticsearch.html
# and filebeat fields.yml version 7.13.4 oss
# Support only server and audit logs from elasticsearch 7++
# Filter Input requirements -> fileset: datatype
#                              server: plain text, json
#                              audit: plain text, json
# 1. Parsing the json from beats
# 2. Parsing the message field containing the elasticsearch log
pipeline:
  - dataTypes:
      - elasticsearch
    steps:
      - json:
          source: raw
      - rename:
          from:
            - log.url
          to: origin.url
      - rename:
          from:
            - log.log.file.path
          to: origin.file
      - rename:
          from:
            - log.host.ip
          to: log.local.ips
      - rename:
          from:
            - log.host.mac
          to: log.local.macs
      - rename:
          from:
            - log.host.hostname
          to: origin.host
      - rename:
          from:
            - log.event.dataset
          to: log.eventDataset
      - rename:
          from:
            - log.agent.version
          to: log.agentVersion
      - rename:
          from:
            - log.host.os.kernel
          to: log.osVersion
      - rename:
          from:
            - log.host.os.type
          to: log.osType
      - rename:
          from:
            - log.host.architecture
          to: log.cpuArchitecture
      - cast:
          to: '[]string'
          fields:
            - log.local.ips
      - cast:
          to: '[]string'
          fields:
            - log.local.macs
      - grok:
          patterns:
            - fieldName: deviceTime
              pattern: '\[{{.data}}\]'
            - fieldName: log.level
              pattern: '\[{{.data}}\]'
            - fieldName: log.component
              pattern: '\[{{.data}}\]'
            - fieldName: log.nodeName
              pattern: '\[{{.data}}\]'
            - fieldName: log.msg
              pattern: '{{.greedy}}'
          source: log.message
      - trim:
          function: prefix
          substring: '['
          fields:
            - deviceTime
            - log.level
            - log.component
            - log.nodeName
          where: has(log.msg)
      - trim:
          function: suffix
          substring: ']'
          fields:
            - deviceTime
            - log.level
            - log.component
            - log.nodeName
          where: has(log.msg)
      - reformat:
          fields:
            - deviceTime
          function: time
          fromFormat: '2022-01-20T22:52:07,431'
          toFormat: '2024-09-23T15:57:40.338364445Z'
          where: has(deviceTime)
      # Begin parsing when message comes in json format
      - json:
          source: log.message
          where: has(log.msg)
      # Performing json step over the remaining message field (Cases when log.message has a message field inside)
      - json:
          source: log.message
          where: has(log.message)
      # Rename audit fields from json
      - rename:
          from:
            - log.audit_format_version
          to: log.auditFormatVersion
          where: has(log.audit_format_version)
      - rename:
          from:
            - log.audit_category
          to: action
          where: has(log.audit_category)
      - rename:
          from:
            - log.audit_node_host_address
          to: log.auditNodeHostAddress
          where: has(log.audit_node_host_address)
      - rename:
          from:
            - log.audit_node_host_name
          to: log.auditNodeHostName
          where: has(log.audit_node_host_name)
      - rename:
          from:
            - log.audit_request_layer
          to: log.auditRequestLayer
          where: has(log.audit_request_layer)
      - rename:
          from:
            - log.audit_request_origin
          to: log.auditRequestOrigin
          where: has(log.audit_request_origin)
      - rename:
          from:
            - log.audit_request_effective_user_is_admin
          to: log.auditRequestEffectiveUserIsAdmin
          where: has(log.audit_request_effective_user_is_admin)
      - rename:
          from:
            - log.audit_request_effective_user
          to: log.auditRequestEffectiveUser
          where: has(log.audit_request_effective_user)
      - rename:
          from:
            - log.audit_rest_request_path
          to: log.auditRestRequestPath
          where: has(log.audit_rest_request_path)
      - rename:
          from:
            - log.audit_rest_request_params
          to: log.auditRestRequestParams
          where: has(log.audit_rest_request_params)
      - rename:
          from:
            - log.audit_rest_request_headers
          to: log.auditRestRequestHeaders
          where: has(log.audit_rest_request_headers)
      - rename:
          from:
            - log.audit_request_initiating_user
          to: log.auditRequestInitiatingUser
          where: has(log.audit_request_initiating_user)
      - rename:
          from:
            - log.audit_request_body
          to: log.auditRequestBody
          where: has(log.audit_request_body)
      - rename:
          from:
            - log.audit_rest_request_method
          to: log.auditRestRequestMethod
          where: has(log.audit_rest_request_method)
      - rename:
          from:
            - log.audit_request_exception_stacktrace
          to: log.auditRequestExceptionStacktrace
          where: has(log.audit_request_exception_stacktrace)
      - rename:
          from:
            - log.audit_trace_task_id
          to: log.auditTraceTaskId
          where: has(log.audit_trace_task_id)
      - rename:
          from:
            - log.audit_transport_headers
          to: log.auditTransportHeaders
          where: has(log.audit_transport_headers)
      - rename:
          from:
            - log.audit_transport_request_type
          to: log.auditTransportRequestType
          where: has(log.audit_transport_request_type)
      - rename:
          from:
            - log.audit_trace_indices
          to: log.auditTraceIndices
          where: has(log.audit_trace_indices)
      - rename:
          from:
            - log.audit_trace_resolved_indices
          to: log.auditTraceResolvedIndices
          where: has(log.audit_trace_resolved_indices)
      - rename:
          from:
            - log.audit_trace_doc_types
          to: log.auditTraceDocTypes
          where: has(log.audit_trace_doc_types)
      - rename:
          from:
            - log.audit_trace_task_parent_id
          to: log.auditTraceTaskParentId
          where: has(log.audit_trace_task_parent_id)
      - rename:
          from:
            - log.audit_request_privilege
          to: log.auditRequestPrivilege
          where: has(log.audit_request_privilege)
      - rename:
          from:
            - log.audit_compliance_operation
          to: log.auditComplianceOperation
          where: has(log.audit_compliance_operation)
      - rename:
          from:
            - log.node.id
            - log.audit_node_id
          to: log.nodeId
          where: has(log.node.id) || has(log.audit_node_id)
      - rename:
          from:
            - log.node.name
            - log.audit_node_name
          to: log.nodeName
          where: has(log.node.name) || has(log.node.name)
      - rename:
          from:
            - log.cluster.name
            - log.audit_cluster_name
          to: log.clusterName
          where: has(log.cluster.name) || has(log.audit_cluster_name)
      - rename:
          from:
            - log.cluster.uuid
          to: log.clusterUuid
          where: has(log.cluster.uuid)
      # Adding fields from elastic audit json file
      - rename:
          from:
            - log.event.type
          to: log.eventType
          where: has(log.event.type)
      - rename:
          from:
            - log.event.action
          to: action
          where: has(log.event.action)
      - rename:
          from:
            - log.request.id
          to: log.requestId
          where: has(log.request.id)
      # Extracting ip and port from address
      - grok:
          patterns:
            - fieldName: log.origin.address
              pattern: '(.*)\:'
            - fieldName: origin.port
              pattern: '{{.greedy}}'
          source: log.origin.address
          where: has(log.origin.address)
      # Cleaning ip address if has port
      - trim:
          function: suffix
          substring: ':'
          fields:
            - log.origin.address
          where: has(log.origin.address)
      - rename:
          from:
            - log.origin.address
          to: origin.ip
          where: has(log.origin.address)
      # Adding geolocation
      - dynamic:
          plugin: com.utmstack.geolocation
          params:
            source: origin.ip
            destination: origin.geolocation
          where: has(origin.ip)
      # Port field conversion
      - cast:
          fields:
            - origin.port
          to: int
          where: has(origin.port)
      - rename:
          from:
            - log.origin.type
          to: log.originType
          where: has(log.origin.type)
      - rename:
          from:
            - log.url.path
          to: origin.url
          where: has(log.url.path)
      - rename:
          from:
            - log.url.query
          to: log.urlQuery
          where: has(log.url.query)
      - rename:
          from:
            - log.request.method
          to: log.method
          where: has(log.request.method)
      - rename:
          from:
            - log.transport_profile
          to: log.transportProfile
          where: has(log.transport_profile)
      - rename:
          from:
            - log.user.name
          to: origin.user
          where: has(log.user.name)
      - rename:
          from:
            - log.user.realm
          to: log.userRealm
          where: has(log.user.realm)
      - rename:
          from:
            - log.user.run_by.name
          to: log.userRunByName
          where: has(log.user.run_by.name)
      - rename:
          from:
            - log.authentication.type
          to: log.authenticationType
          where: has(log.authentication.type)
      - rename:
          from:
            - log.apikey.name
          to: log.apikeyName
          where: has(log.apikey.name)
      - rename:
          from:
            - log.user.roles
          to: log.userRoles
          where: has(log.user.roles)
      - rename:
          from:
            - log.user.run_as.name
          to: log.userRunAsName
          where: has(log.user.run_as.name)
      - rename:
          from:
            - log.user.run_as.name
          to: log.userRunAsName
          where: has(log.user.run_as.name)
      # Casting new fields after json parsing
      - cast:
          to: '[]string'
          fields:
            - log.auditTraceIndices
            - log.auditTraceResolvedIndices
            - log.indices
            - log.userRoles
      # Adding severity based on log.level
      - add:
          function: 'string'
          params:
            key: severity
            value: 'high'
          where: log.level == true && (log.level == "CRITICAL" || log.level == "FATAL" || log.level == "ERROR")
      - add:
          function: 'string'
          params:
            key: severity
            value: 'medium'
          where: log.level == true && log.level == "WARN"
      - add:
          function: 'string'
          params:
            key: severity
            value: 'low'
          where: log.level == true && (log.level == "INFO" || log.level == "DEBUG" || log.level == "TRACE")

      # Removing unused fields
      - delete:
          fields:
            - log.service
            - log.metadata
            - log.agent
            - log.host
            - log.event
            - log.ecs
            - log.log
            - log.fileset
            - log.cluster
            - log.node
            - log.opaque_id
            - log.trace_id
            - log.x_forwarded_for
            - log.request
            - log.url
            - log.user
            - log.apikey
            - log.authentication
            - log.origin

      # Droping unwanted logs
      - drop:
          where: has(log.eventDataset) && has(log.component) && ( (log.eventDataset != "elasticsearch.server" && log.eventDataset != "elasticsearch.audit") || (log.eventDataset == "elasticsearch.server" && (log.component.matches("(A|a)udit")==false && log.component.matches("(S|s)(S|s)(L|l)")==false && log.component.matches("(S|s)ecurity")==false ) ) )
